services:
  flask:
    image: flask
    build:
      context: flask
      dockerfile: Dockerfile
    privileged: True
    command: flask run --host=0.0.0.0  --debug
    expose:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/share:/share
      - ${PWD}/flask:/opt/flask
    networks:
      - appstream
  nginx:
    image: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ${PWD}/share/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
    restart: always
    networks:
      - appstream
  itksnap:
    image: itksnap
    build:
      context: itksnap
      dockerfile: Dockerfile.turbovnc
    deploy:
      replicas: 0
    expose:
      - "8888"
    networks:
      - appstream
networks:
  appstream: